In [1]:
import pandas as pd

test = pd.read_excel("covid_guayaquil_limpio.xlsx")
display(test.head(5))


tweet.created_at tweet.user.screen_name tweet.user.location  \
0 2020-05-19 05:23:16        _carolinaromero           Guayaquil   
1 2020-05-24 20:24:12                _emigar           Guayaquil   
2 2020-05-17 22:35:40                _emigar           Guayaquil   
3 2020-05-19 02:35:18                  _fbsc           Guayaquil   
4 2020-05-19 02:32:52                  _fbsc           Guayaquil   

                                     tweet_full_text  Depresivo  \
0  veo tanta gente quejandose servicio internet f...          0   
1  expresoec lenin incapaces donar mes trabajados...          0   
2         twitter lenin obituario farandula pandemia          0   
3                         mashirafael favor comparte          0   
4                             krncita favor comparte          0   

   Cadena_depres titular  
0              0    doc1  
1              0    doc2  
2              0    doc3  
3              0    doc4  
4              0    doc5

In [2]:
anterior=test["tweet.user.screen_name"][0]
matr=[]
aux=[]
long=len(test["tweet.user.screen_name"])

In [3]:
for i in range(long):
    usuario=test["tweet.user.screen_name"][i]
    #print(f"{usuario} y {anterior}")
    if test["tweet.user.screen_name"][i] == anterior:
        aux.append(test["Depresivo"][i])
    else:
        if aux==[]:
            aux.append(test["Depresivo"][i])
        matr.append(aux)
        aux=[]
        aux.append(test["Depresivo"][i])
    if i == long-1:
        aux=[]
        aux.append(test["Depresivo"][i])
        matr.append(aux)
    anterior=test["tweet.user.screen_name"][i] 
    

In [4]:
leng=[]
for i in range(len(matr)):
    leng.append(len(matr[i]))
maxim=max(leng)
print(maxim)

95


In [5]:
m = max(leng)
[i for i, j in enumerate(leng) if j == m]

[1805]

In [6]:
for i in range(len(matr)):
    if len(matr[i])<10:
        while len(matr[i])<10:
            matr[i].append(0)
    elif len(matr[i])>10: 
        #print(f"prev en {matr[i]}")
        matr[i]=matr[i][0:10]
        #print(f"aft en {matr[i]}")
#print(matr)

In [7]:
leng=[]
for i in range(len(matr)):
    leng.append(len(matr[i]))
maxim=max(leng)
print(maxim)

leng=[]
for i in range(len(matr)):
    leng.append(len(matr[i]))
maxim=max(leng)
print(maxim)

10
10


In [8]:
X=matr

In [9]:
anteriorY=test["tweet.user.screen_name"][0]
matrY=[]
auxY=[]
longY=len(test["tweet.user.screen_name"])

In [10]:
for i in range(longY):
    usuarioY=test["tweet.user.screen_name"][i]
    #print(f"{usuario} y {anterior}")
    if test["tweet.user.screen_name"][i] == anteriorY:
        auxY.append(test["Cadena_depres"][i])
    else:
        if auxY==[]:
            auxY.append(test["Cadena_depres"][i])
        matrY.append(auxY)
        auxY=[]
        auxY.append(test["Cadena_depres"][i])
    if i == longY-1:
        auxY=[]
        auxY.append(test["Cadena_depres"][i])
        matrY.append(auxY)
    anteriorY=test["tweet.user.screen_name"][i] 

In [11]:
#print(matrY)
Y=[]
for i in matrY:
    Y.append(i[0])

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn import metrics
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
from sklearn import preprocessing
import numpy as np

In [13]:
#tweet_full_text
tex=[]
var=""
for i in test["tweet_full_text"]:
    var=str(i).split()
    tex.append(var)
print(tex[0])

['veo', 'tanta', 'gente', 'quejandose', 'servicio', 'internet', 'fijo', 'cnt', 'tvcable', 'agradezco', 'cielo', 'habernos', 'cambiado', 'servicio', 'empezado', 'pandemia']


In [14]:
palab=[]
t=0
for i in tex:
    for j in i:
        palab.append(j)
        t+=1
dic=set(palab)
pal=[]
for i in dic:
    pal.append(i)

In [15]:
le=preprocessing.LabelEncoder()
le.fit(pal)

LabelEncoder()

In [16]:
X_train=[]
tex_test=[['no','me','siento','bien','maldita','depresion','hdp','soledad','mala',],
        ['que','bien','feliz','siento','trabajo','linea','mejor'],
        ['corrupcion','ratas','gobierno','saben','hacen'],
        ['pruebas','covid','tratamiento','hospital','mascarillas'],
        ['depresion','real','mal','siento','triste','llanto'],
        ['musica','vida'],
        ['solo','mal','depresion','loco','soledad']]
anadir=np.zeros([7,16])
X_test=[]
Y_test=[1,0,0,0,1,0,1]
tem=[]
for i in range(len(tex)):
    tem=le.transform(tex[i])
    X_train.append(tem)
tem=[]
for i in range(len(tex_test)):
    tem=le.transform(tex[i])
    X_test.append(tem)
#print(anadir)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [17]:
y_train=[]
for i in test["Depresivo"]:
    y_train.append(i)
#print(y_train)

In [18]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn import metrics

df2=pd.DataFrame(X_train)
df2=df2.fillna(0)
display(df2.head(5))


nb = MultinomialNB()
nb.fit(df2,y_train)

0        1       2        3        4        5       6       7        8   \
0  13052  12281.0  5877.0  10531.0  11764.0   6956.0  5537.0  2343.0  12752.0   
1   5290   7554.0  6576.0   4216.0   8283.0  12589.0  9261.0     0.0      0.0   
2  12765   7554.0  8895.0   5422.0   9261.0      0.0     0.0     0.0      0.0   
3   8107   5443.0  2521.0      0.0      0.0      0.0     0.0     0.0      0.0   
4   7392   5443.0  2521.0      0.0      0.0      0.0     0.0     0.0      0.0   

      9  ...    23   24   25   26   27   28   29   30   31   32  
0  399.0 ...   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1    0.0 ...   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2    0.0 ...   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3    0.0 ...   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4    0.0 ...   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 33 columns]

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [19]:
for i in X_test:
    while len(i)<32:
        i=np.append(i,0, axis=None)
print(X_test)

[array([13052, 12281,  5877, 10531, 11764,  6956,  5537,  2343, 12752,
         399,  2220,  6095,  1788, 11764,  4573,  9261], dtype=int64), array([ 5290,  7554,  6576,  4216,  8283, 12589,  9261], dtype=int64), array([12765,  7554,  8895,  5422,  9261], dtype=int64), array([8107, 5443, 2521], dtype=int64), array([7392, 5443, 2521], dtype=int64), array([ 1679,  8559, 11920,  7833, 13285,  9398, 11930,  5623,  7877,
       12579,  3785, 10192, 11160,  3193,  3055,  8792,  4329],
      dtype=int64), array([ 4196,  6339, 11815, 12710, 10555,  7764, 11475,  7429, 11853],
      dtype=int64)]
